# Generated by Django 4.1.7 on 2023-06-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0013_salesorder_sales_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='hsn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
