# Generated by Django 4.1.7 on 2023-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0015_additem_inventorystock'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additem',
            name='inventorystock',
            field=models.CharField(default='', max_length=255),
        ),
    ]
