# Generated by Django 4.1.7 on 2023-06-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0016_additem_stock_alter_additem_inventorystock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='inventorystock',
        ),
    ]
