# Generated by Django 4.1.7 on 2023-06-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0017_remove_additem_inventorystock'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='tax',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
