# Generated by Django 4.1.7 on 2023-07-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0025_remove_comments_item_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_item',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem'),
        ),
    ]
