# Generated by Django 4.1.7 on 2023-07-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0026_comments_item_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments_item',
            name='item',
        ),
    ]
