# Generated by Django 4.1.7 on 2023-07-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0028_comments_item_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Account_type',
            field=models.CharField(choices=[('1', 'EXPENSE'), ('2', 'Cost of Goods Sold'), ('3', 'Fixed Asset')], max_length=255),
        ),
    ]
