# Generated by Django 4.1.7 on 2023-07-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0029_alter_purchase_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='stock_status',
            field=models.TextField(default='active'),
        ),
    ]
