# Generated by Django 4.1.7 on 2023-07-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0030_additem_stock_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='stock_status',
        ),
    ]
